language: java # set desired language

dist: trusty

addons:
  apt:
#    sources:
#      - google-chrome # if your project contains tests need to be run on chrome include these lines
    packages:
      - google-chrome-stable

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - chmod +x src/main/resources/selenium/linux/chromedriver
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start &
#  - sleep 3
##  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16

script:
  # perform build and run commands here
  - mvn test