language: java

env:
  global:
  - secure: A7fOVs2FwXsECNAo4B6HtiSjVADC7G+7FNM2O1fwELEtkzMkHUHXaWKsx0q/17JJRQr9pUWXtVLqfDOJDdBwgKJ7jyPzIHM0+bKFVoSGO5+u5vL4hz+RXg8X7/m4Lm8i8my5OpWOaX6B9ruhkDRwbmk1z3zM07eLpziTAUWaU29BZpS/f07QAjkA+e/qMsqYaMAbWIuXyxbVt2QHC8dIKPNwPmJ2Oxl15mZIibrVBnlGV9E8p2s8vHtYTEaCLfmGvZl3flt+A0mZg07q3SJhixYGgQW2WoTePV5DLuwYvjtVMoT1cK1Fqa04miG4+Qk86mzwidMRMzxzO2CWk40EOl0fvqEiHMO93OHbN5bn1zIm+neHxzy30ozXAo1olu/R0xn4DZDBTMPQ5WY6Lg65lA5kyuT4mxFgUkVgTQ2sCfs0WIebYWzXvFXaSEGy44uU4Ecssu76IAjHs8YVoiWrrUDi47r7PV64cw4ESUYG1Ay4G68rf+kkXOEtTLvG+H5DRJLph9O9ljgNd07cfitjf6cv7EAMdRCeTeaa6WbHP0BJ0G38qox80TBymQSPYRgXp4Uh3seuGD61LVqfyOdsZinhedxx0p53/4CeXBEMKCo+xaTDNnuXJCIG0mMdmluOlnzxYbGnAMr5jYcrmOlssSLQCp6uh6RFB97hH8Xsfwk=
  - secure: d4CYpvNzJcckKngPkc/Eu3cNOncoQOa0EmyWsBRg6T5kPnhSgBfFjEketP4dBjOBoz0AsIf0lefjLJDxqoTbkchuGR+ljuLab37NdcQJti2h+8HjsccfoW/E4GidB0htb53QErd1QrnYsF1iHeAVzNPLzQ4WXBRfOz19oFoD3pibVFmETF5Ss9y883+o7o7KNjNBZ1C6ukMAzvhInmBDF64gyjBr1kFsbypRdhmgEHMBA6LyCD29P4E+2d/LRk9igJx01ADkBcSiCXWcD+CydUmUKjMej6psbukU1B9njupxGTcuNBRUGwtvYDSXpK2Mxu1c8D2OOFnmSvI6T015h2guLBmN6FwiEC0KMPKpYliJZpBErQuNPsqb+kUu530vsd2Wrk1kYjPEZb3X+X9bygW7K09TCNOfs9SNR7oiBFK/w9MdVmzC009n9ElkJzP0eKc4z/iaSRZUwWKxgA4RKwIFjpmzA2WXCPx5yMghEeX+pXamOhFqS5bNgOVD47QmW93Y32BpqAuYYhvs9guoGzartiC+UpRFPlgRD4xqjsCJoqKgDGocRDVd2fo/xyZMmr3+O1iKo/abk14ec0OLqhx1FuF6Wq0bqlTjB3IjLb1jJFu98id+NUV6z9Dms71qr3ay6FVch8thPANhhFM5BRFIUPxzXMIUd0URYXY2kjo=
  - STAGE=dev
#  - STAGE=$TRAVIS_BRANCH
  - REGION=us-east-1
  - BUILD_START=$(date +%s)
#SES keys
  - secure: mArXL6KsHG4xigDdxik75bCjBI2fiwQQQ3JrzwQHquHIOpSYtPLn8cex3zZRk8tj46dLHR7PUsWmVBPU8inGucjjdAydVsY26FBE/QHSBqgOI+HOV8+L1X3phKWfAWM4HFm9qMD3nTrhKJBIswtlez+HdP9KAfYfzE+2ZAYenp7Wj3CnZwgfEZ73yRMvG7/AUDQ/VT4Gxy3L8Mjj5e9kynUcHoNmJSCusm6425dGq+YwnNUzgsA1LievBaY0Dkp82G/QmSvvpkpNndy0lkhNrSUzam4mNxDTtf+5l6s4kV/qyB4KCJBFIeokbeeVyyTXuN8iZkDWeT6oSVFVy9k9mydSTgpFGHA5z00cjvkUPVZRhro1LRX4lBpRWXdIFYw6CD5cbymKnojkgb9cDg5pYSEU7HeezD5JVj3+l30dYISj2Hk/aK+sFT+VDBzYZyueDcbYwSlLpdgMV8am/Hp9ZxmjTBj9jbYzIaJfMjIpB0kGwQOUcyeb8ph5jnsCYZ3xlCgYHF1iXIbWVyGiSTGbL8a31/nRfnWuVO1uGzyokJj6M08gRLO5wyYpXz7XFh4knBBa8AK88pH2IBa7Kh60wTQlf19PtX8ZYxFY5sxjgpjTL/2zWGan1g1+eutlsJ2xm6rWgikrsLU4buazTJ1lsOqrYYs4FR8+WBrZnlx2jmE=
  - secure: cWOg/MT5gA/J8ueE7rFQMrVXwTK1yv6M7geMBt/198e+kTCk0m8xJmp0vT91qQX1O0FZJMPfdmz6xcDmuexfJ6/SyiJ4mu00/CxqouLOjaenytEMFAMomDqMcvJkSTWomSKhBAhSxwzbxaSimItbRh/4RfqQ8aLZ1Wolgt2+keoQKI927GvIhUqSEnYeOOyjAxz0CwjVih4pZiUXhT1cyHtl6w+24B9hkcVKIwiTvKRO9gZ55xlK1voma1K8K2n43A3NpVUgg2tkkeC+CHNunRTo44N1CHwjbdvkXjXmtVSHcQOE/ti5VobLqyHm/PRYKsTdy2UYJpm30PpJceg+S59d8qFFMOxMEaWHtQYQDj8EF4dbjc1MY9FdH6VVhrb41holHxUX0hT97OM7qMwHrvtBqRozxwIeoNrcF4Ez16ndoPwXrsqW1UVIvZJToA5dHkqIfqbYbjAIvalLRs2JXtdbh74noPq8AgdLWLTqxZR/Y9N/mIW0LvyZNs2sTBILBtfpLX+G7SNR9LlWx7MLYwYo1MiZV7zKl9NS9sGFa1snWvhOpJpb2MZbpvMFKS2yCluAZHx3WaMjyCw4FSE+11NHdROkhGlLqzcHnrtlcEbD8iK59dd6O3QrpSa8ezYPgfpaImQ7GgGzilGhDfsBXXX4rWu2pssXWMqChQGSPYI=
# Slack webhook
  - secure: GMEbiTh4QsJX58ZB5Ov6CxtxXCan9yAqK2IJOjkxU01m96ejpFChJQ78o52FUqQ2Lvk104/UUbmfr+rS/03IOtiXdcBwsSFGlDDiKn0mVHV4jkzmgz+6jf5g2+hW60raKY8KsucmuMvy72aq47GWX9uos3AtBBSHP4sVtKCY7HWu7y7wJkOX8CA3MM5QZ2oLohd8QOLPR185PhoK84roFcp9pslAts9xPUg35mFrI7Tcj3kucWD08Xkz3bhaorLiq0osabPIr4zDMvXp/26ZhXLs8kQTdSD1C7aP5rr4yhtPE9jE+XmU7s7OHO6J6D7HgT3VEGY11Y+JI+D+OXqpxxQoczIOZ7K6YChq93DOCJxOc4CgVBDEI+q7hq52RIzgHbdCrvyFfxNwD0DYldahP1mk42q8bCl+BHBw447n/i8LTRrbDuvmNPwdAJriW3UItb1lcaeWtFVbfSd1e1MMYrT09WlK0f/N+CXv1+mFu3Q5gU2wdrdT6gO+CVlYCf/b1zDeW8YhX5KI5sGB1CMQRJ77Lk3SZxozaieNCfewPYAsuVylvTqji0VGo3AEocTpQXnP77ni5CrCrScPfLOWRnZDb6Lb/nETeUhx+P48PeGc1zye/tOYwaudc1O1aj5NVBztyu3Jh+ZR4Tw9hlTTXttoyriLYePrdCng6zYNNI8=

branches:
 only:
   - jar-inprogress

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
      - oracle-java8-installer
      - oracle-java8-set-default

script:
#virtual framebuffer for ui part of the test
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start &
#  - sleep 5
# run tests from builded .jar
  - cd target
#  - chmod +x iot-auto-fat.jar
#  - java -jar iot-auto-fat.jar

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "iotsyst.builds"
    skip_cleanup: true
    local_dir: iot-auto-fat.jar
    upload-dir: dashboard/auto_tests
    on:
      all_branches: true