language: java # set desired language

dist: trusty

addons:
  apt:
    sources:
      - google-chrome # if your project contains tests need to be run on chrome include these lines
    packages:
      - google-chrome-stable


before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024" # running virtual display on desired port with desired settings
  - sleep 3

script:
  # perform build and run commands here
  - mvn test