language: java
env:
  global:
   - secure: "tixXAHJdxWWDrIXQEXh3HX6dLPDgtypaO2cGL2x+nBKK0MZLYPZ79BGitzLTBXVjpPBp7Yd09SiHlW/pNMO4Fz2Yhzgn6FxFHERm7tEg7D4gvU7myF7FYXeYDyZ9ZxF/dnc+fgc9S6kS9MHiiIg7RspqjKQhRXZvo2AuLWeB9dLatP/o745wLnskg0cGIc+wxoIUlR9MMMAJSVqjS2dsLbsE36QML8s4EkDXQ9qzpotbSyywb+o+QImyJVl3qaqyXv/dI1Q+2xGQgFObGfs9Rkphpt5FdmJbtOHRG97hpJksUNSG2skd0AlDdbl6iqGGKIEmYLyIjLlqiWRBJS1BkUQs7m8XB9cmnHJmmLu0LSq5tx3YpwU05OQJTx1WyjzutN3H1nGLeXMxnoyomkCxTch791fLq4cmTwnpBTEHhdayAkeBIJk2Wj1j+ZvDpnS5HlAVfRePM1eOlJfH4U1jkU0gpxFbPnNTjRQb60FbGhqkTXdg1GJPode2XMWFOo4pVObRkzsLtBdmhl+dVq/48K/bP6d8A1TrBQovgnEMzPIZKqW+TN/Tmr6ycWd33+OxF5tfyWmcSAZKP+9wrlfmSnCqmDlIf7GQDcOHq6QKa9+FwxQx47KIBdYy5tPhtikoocpv2CbnEOCceU+mgPyRNq5UDW93YLeZxdd3wyDklA0="
   - secure: "b/nYqz/ADZNqpfARLDfmxxAwElcOFCjedIJa/oZJNEFS8iO4Qw/S8koJ7IK9X8OTPYWxZKQzABAPEdTPJHfxbXDwKe+0p88yRlelZNJKrwSwIa7cz08WvMBfDlKHjJCR8qjtNF+gkHO5Zz6ct7smfJDcu/TGINKNHsdfLiDhKFkHXsYHqAcIGrzl+CTAay8l9ebDpRJEoPjthvh0iJSdrA5Uz03XsB7sKr5iaN6Jiho6MsCoWSMTj+xM9RBxKrtD3VtGx3elVabDWZNobq9XHVHuy+xSb+9AnHmMrc/9YXRIxgRtwMN8+gryFNU1eHN7dEGJWhEdoX6QCht1sG46OfQw3LohkKeq8wgYQPdCx2nLSyFYsMFcJrJwVA/CVYGC/ptkQKnHjeKLEC91jD0WET1GabG5il4vhlR8EhX5cYl07m1MTj1saqQuyhVhkRJqedardaEtQBqGtSKj7C9jS6yxsaRgQHq3o/Aso0snBu0OUfjdT7vMlomG9Wk3k1e0jDtIo2eOA0HKIwK6Qr/rtgC/MwAFJZ3CTOVtuKmZFPf2/qASkNOCF9ur/pqajqeTVe+c5g97N6oOc9sA70uwbI6o2cR8ajKPP66o/8dPmBxgix0zXxVE97oxY5S2Yw6qst3NsdGEq0jHjJKjKiOQy0I1HSy9eviFoFeZCDxnSCA="
branches:
 only:
   - master
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable
      - oracle-java8-installer
      - oracle-java8-set-default
install:
  - mvn package -DskipTests
script:
#uncomment all lines below to be able to launch tests from travis-ci environment
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start &
#  - sleep 5
  - cd target
#  - chmod +x iot-auto-fat.jar
#  - java -jar iot-auto-fat.jar
  - mkdir upload
  - cp -v iot-auto-fat.jar upload/iot-auto-fat.jar

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "iotsyst.builds"
    skip_cleanup: true
    local_dir: upload
    upload-dir: dashboard/auto_tests
    on:
      all_branches: true