language: java # set desired language

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
      - oracle-java8-installer

before_script:
  - chmod +x src/main/resources/selenium/linux/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  # perform build and run commands here
  - mvn clean test
