language: java

dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
      - oracle-java8-installer
      - oracle-java8-set-default

script:
#virtual framebuffer for ui part of the test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 5
# run tests from builded .jar
  - cd target
  - chmod +x iot-auto-fat.jar
  - java -jar iot-auto-fat.jar
