language: java # set desired language

dist: trusty

addons:
  apt:
#    sources:
#      - google-chrome # if your project contains tests need to be run on chrome include these lines
    packages:
      - google-chrome-stable

before_script:
  - chmod +x src/main/resources/selenium/linux/chromedriver
  - export DISPLAY=:99.0
#  - Xvfb :99 -screen 0 1920x1024x24 > /dev/null 2>&1 &
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  # perform build and run commands here
  - mvn test