env:
  matrix:
  - CACHE_NAME=DASHBOARD
language: node_js
node_js:
  - '6.10.2'
addons:
  apt:
    packages:
      - google-chrome-stable
      - oracle-java8-installer
      - maven

before_script:
- chmod +x src/main/resources/selenium/linux/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3

script:
 - mvn clean test